---
name: Auto / Protected Branches

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deploy:
    name: Deploy
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml

