version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Customizer
  - Levon
  - makerlab
  - Openscad
  - pyinvoke
  - pylint
  - pythonopenscad
  - solidpython
  - venv
ignoreWords: []
import: []
