---
name: setup_uv
author: Fireball 3D
description: Install and Setup Python UV
runs:
  using: composite
  steps:
    - name: Install UV
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH  # ensure uv is in PATH

    # - name: Install Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: 3.13

    # - name: Install Python
    #   shell: bash
    #   run: |
    #     uv python install 3.13 --preview

    - name: Create Python Virtual Environment
      shell: bash
      run: |
        uv venv .venv --python 3.13

    - name: Activate Python Virtual Environment
      shell: bash
      run: |
        source .venv/bin/activate

    - name: Download Project Libs
      shell: bash
      run: |
        uv sync

