---
name: Auto / Protected Branches

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  style:
    name: Style
    uses: ./.github/workflows/test_style.yml

