---
name: Auto / Feature Branches

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  style:
    name: Style
    uses: ./.github/workflows/test_style.yml
